sbatch cmd-ad-0.sh
sbatch cmd-ad-1.sh
sbatch cmd-ad-2.sh
sbatch cmd-ad-3.sh
sbatch cmd-ad-4.sh
sbatch cmd-ad-5.sh
sbatch cmd-ad-6.sh
sbatch cmd-ad-7.sh
sbatch cmd-ad-8.sh
sbatch cmd-ad-9.sh
sbatch cmd-bbc-0.sh
sbatch cmd-bbc-1.sh
sbatch cmd-bbc-2.sh
sbatch cmd-bbc-3.sh
sbatch cmd-bbc-4.sh
sbatch cmd-bbc-5.sh
sbatch cmd-bbc-6.sh
sbatch cmd-bbc-7.sh
sbatch cmd-bbc-8.sh
sbatch cmd-bbc-9.sh
